version: 2

machine:
  services:
  - docker

jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - setup_remote_docker:   # (2)
           docker_layer_caching: true # (3)
           version: 18.06.0-ce
      - run:
          name: Build Workflow Docker Image
          command: |
            docker build . --file Dockerfile --tag my-image-name:$(date +%s)
